# Generated by Django 6.1.1 on 2026-09-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="USSDSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("phone_number", models.CharField(db_index=True, max_length=30)),
                (
                    "current_state",
                    models.CharField(db_index=True, default="START", max_length=50),
                ),
                ("business_id", models.IntegerField(blank=True, null=True)),
                ("category_id", models.IntegerField(blank=True, null=True)),
                ("product_id", models.IntegerField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("temp_data", models.JSONField(blank=True, default=dict)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
