version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: shopx_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shopx_user -d shopx_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: shopx_web
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - AFRICASTALKING_USERNAME=${AFRICASTALKING_USERNAME}
      - AFRICASTALKING_API_KEY=${AFRICASTALKING_API_KEY}
      - AFRICASTALKING_SENDER_ID=${AFRICASTALKING_SENDER_ID}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
