# Generated by Django 5.0.7 on 2026-09-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("BUSINESS_OWNER", "Business Owner"),
                    ("BUSINESS_STAFF", "Business Staff"),
                    ("CUSTOMER", "Customer"),
                ],
                default="BUSINESS_OWNER",
                help_text="Role of the authenticated platform user.",
                max_length=20,
            ),
        ),
    ]
