# Generated by Django 6.1.1 on 2026-09-24 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="inventory",
                        serialize=False,
                        to="catalog.product",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("reserved_quantity", models.PositiveIntegerField(default=0)),
                ("low_stock_threshold", models.PositiveIntegerField(default=5)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Inventories",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("quantity__gte", models.F("reserved_quantity"))
                        ),
                        name="quantity_gte_reserved",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reserved_quantity__gte", 0)),
                        name="reserved_quantity_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gte", 0)),
                        name="quantity_non_negative",
                    ),
                ],
            },
        ),
    ]
