# Generated by Django 5.0.7 on 2026-09-26 19:38

from django.db import migrations, models
from django.db.models import F, Q


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_image"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=Q(quantity__gte=F("reserved_quantity")),
                name="quantity_gte_reserved",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=Q(reserved_quantity__gte=0),
                name="reserved_quantity_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=Q(quantity__gte=0),
                name="quantity_non_negative",
            ),
        ),
    ]
