# Generated by Django 6.1.1 on 2026-09-24 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="Valued Customer", max_length=150
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("area", models.CharField(max_length=150)),
                ("street", models.CharField(blank=True, default="", max_length=255)),
                (
                    "house_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("landmark", models.CharField(blank=True, default="", max_length=255)),
                ("delivery_note", models.TextField(blank=True, default="")),
                ("city", models.CharField(default="Local", max_length=100)),
                ("state", models.CharField(default="State", max_length=100)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Addresses",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
    ]
