# Generated by Django 6.1.1 on 2026-09-26 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recipient", models.CharField(db_index=True, max_length=30)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("ORDER_CREATED", "Order Created"),
                            ("BUSINESS_NEW_ORDER", "Business New Order"),
                            ("ORDER_ACCEPTED", "Order Accepted"),
                            ("ORDER_REJECTED", "Order Rejected"),
                            ("CUSTOMER_CONFIRMED", "Customer Confirmed"),
                            ("ORDER_READY", "Order Ready"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("ORDER_DELIVERED", "Order Delivered"),
                            ("ORDER_CANCELLED", "Order Cancelled"),
                            ("ORDER_STATUS_UPDATE", "Order Status Update"),
                        ],
                        db_index=True,
                        default="ORDER_STATUS_UPDATE",
                        max_length=30,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "provider",
                    models.CharField(
                        db_index=True, default="africastalking", max_length=40
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("DELIVERED", "Delivered"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_notifications",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "notification_type", "recipient"),
                        name="unique_order_sms_notification",
                    )
                ],
            },
        ),
    ]
